/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces.tutorial;
import interfaces.*;
import java.awt.Font;
import java.io.InputStream;
import javax.swing.JPanel;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.Color;
/**
 *
 * @author frann
 */
public class Paso4 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Paso4.class.getName());

    /**
     * Creates new form prueba
     */
    public Paso4() {
        initComponents();
        this.setLocationRelativeTo(null); // abrir ventana en el centro 
        this.setTitle("PMySCRUM - Tutorial");
        
            // ===============================================
            // CÓDIGO PARA CARGAR Y APLICAR LA FUENTE EXTERNA
            // ===============================================
            try {
                // 1. Obtener el flujo de datos (InputStream) de la fuente desde el JAR
                InputStream is = Paso4.class.getResourceAsStream("/fonts/PressStart2P.ttf");

                // Verifica que la ruta es correcta; si is es null, el archivo no se encontró.
                if (is != null) {
                    // 2. Crear un objeto Font a partir del archivo
                    Font customFont = Font.createFont(Font.TRUETYPE_FONT, is);

                    // 3. Establecer el tamaño y estilo (ej. tamaño 24)
                    Font sizedFontTitulo = customFont.deriveFont(Font.BOLD, 24f); 
                    Font sizedFontTexto = customFont.deriveFont(Font.BOLD, 16f); 
                    Font sizedFontTexto2 = customFont.deriveFont(Font.BOLD, 12f); 

                    // 4. Aplicar la fuente al JLabel creado en el diseñador
                    
                    // titulo del header 
                    titulo.setFont(sizedFontTitulo); 
                    
                    // texto del paso 2
                    textoPaso4.setFont(sizedFontTexto);
                    textoPaso4.setForeground(java.awt.Color.WHITE);
                    texto2Paso4.setFont(sizedFontTexto);
                    texto2Paso4.setForeground(java.awt.Color.WHITE);
                    texto3Paso4.setFont(sizedFontTexto);
                    texto3Paso4.setForeground(java.awt.Color.WHITE);
                    
                    
                    // texto central
                    paso4TextoCentral1.setFont(sizedFontTexto2);
                    paso4TextoCentral2.setFont(sizedFontTexto2);
                    paso4TextoCentral3.setFont(sizedFontTexto2);
                    paso4TextoCentral4.setFont(sizedFontTexto2);
                    
                } else {
                    System.err.println("Error: Archivo de fuente no encontrado en la ruta /fonts/PressStart2P.ttf");
                }

            } catch (Exception e) {
                // Captura errores como problemas de formato de fuente o I/O
                System.err.println("Error al cargar la fuente: " + e.getMessage());
            }
        
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        contenido = new javax.swing.JPanel();
        paso2 = new javax.swing.JPanel();
        textoPaso4 = new javax.swing.JLabel();
        texto2Paso4 = new javax.swing.JLabel();
        texto3Paso4 = new javax.swing.JLabel();
        paso4TextoCentral1 = new javax.swing.JLabel();
        paso4TextoCentral2 = new javax.swing.JLabel();
        paso4TextoCentral3 = new javax.swing.JLabel();
        paso4TextoCentral4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        imagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo.setBackground(new java.awt.Color(255, 255, 255));

        header.setBackground(new java.awt.Color(185, 188, 240));

        titulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 0, 0));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Tutorial del Juego");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(titulo)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        contenido.setBackground(new java.awt.Color(255, 255, 255));

        paso2.setBackground(new java.awt.Color(51, 51, 255));
        paso2.setForeground(new java.awt.Color(0, 0, 0));
        paso2.setToolTipText("");

        textoPaso4.setText("Paso 4: ");

        texto2Paso4.setText("Resultados");

        texto3Paso4.setText("Retroalimentación");

        javax.swing.GroupLayout paso2Layout = new javax.swing.GroupLayout(paso2);
        paso2.setLayout(paso2Layout);
        paso2Layout.setHorizontalGroup(
            paso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paso2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(paso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoPaso4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(paso2Layout.createSequentialGroup()
                        .addGroup(paso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(texto3Paso4)
                            .addComponent(texto2Paso4))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        paso2Layout.setVerticalGroup(
            paso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paso2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(textoPaso4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(texto2Paso4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(texto3Paso4)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        paso4TextoCentral1.setBackground(new java.awt.Color(255, 255, 255));
        paso4TextoCentral1.setForeground(new java.awt.Color(0, 0, 0));
        paso4TextoCentral1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paso4TextoCentral1.setText("Verás si tus decisiones fueron un beneficio o si");

        paso4TextoCentral2.setForeground(new java.awt.Color(0, 0, 0));
        paso4TextoCentral2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paso4TextoCentral2.setText("afectaron al proyecto");

        paso4TextoCentral3.setForeground(new java.awt.Color(0, 0, 0));
        paso4TextoCentral3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paso4TextoCentral3.setText("Tu resultado es tu retroalimentación");

        paso4TextoCentral4.setBackground(new java.awt.Color(255, 255, 255));
        paso4TextoCentral4.setForeground(new java.awt.Color(0, 0, 0));
        paso4TextoCentral4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paso4TextoCentral4.setText("¡Aprende con ella!");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/jugarBtn.png"))); // NOI18N

        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/retro.png"))); // NOI18N

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(contenido);
        contenido.setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenidoLayout.createSequentialGroup()
                .addGroup(contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paso4TextoCentral1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenidoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(paso4TextoCentral3, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenidoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(paso4TextoCentral4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(contenidoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(paso4TextoCentral2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenidoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(imagen)
                .addGap(324, 324, 324))
            .addGroup(contenidoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(paso2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenidoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(250, 250, 250))
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenidoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(paso2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(paso4TextoCentral1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(paso4TextoCentral2)
                .addGap(18, 18, 18)
                .addComponent(paso4TextoCentral3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(paso4TextoCentral4)
                .addGap(50, 50, 50)
                .addComponent(imagen)
                .addGap(54, 54, 54)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Paso4().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenido;
    private javax.swing.JPanel fondo;
    private javax.swing.JPanel header;
    private javax.swing.JLabel imagen;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel paso2;
    private javax.swing.JLabel paso4TextoCentral1;
    private javax.swing.JLabel paso4TextoCentral2;
    private javax.swing.JLabel paso4TextoCentral3;
    private javax.swing.JLabel paso4TextoCentral4;
    private javax.swing.JLabel texto2Paso4;
    private javax.swing.JLabel texto3Paso4;
    private javax.swing.JLabel textoPaso4;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
