/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces.tutorial;
import interfaces.*;
import java.awt.Font;
import java.io.InputStream;
import javax.swing.JPanel;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.Color;
/**
 *
 * @author frann
 */
public class Paso2 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Paso2.class.getName());

    /**
     * Creates new form prueba
     */
    public Paso2() {
        initComponents();
        this.setLocationRelativeTo(null); // abrir ventana en el centro 
        this.setTitle("PMySCRUM - Tutorial");
        
            // ===============================================
            // CÓDIGO PARA CARGAR Y APLICAR LA FUENTE EXTERNA
            // ===============================================
            try {
                // 1. Obtener el flujo de datos (InputStream) de la fuente desde el JAR
                InputStream is = Paso2.class.getResourceAsStream("/fonts/PressStart2P.ttf");

                // Verifica que la ruta es correcta; si is es null, el archivo no se encontró.
                if (is != null) {
                    // 2. Crear un objeto Font a partir del archivo
                    Font customFont = Font.createFont(Font.TRUETYPE_FONT, is);

                    // 3. Establecer el tamaño y estilo (ej. tamaño 24)
                    Font sizedFontTitulo = customFont.deriveFont(Font.BOLD, 24f); 
                    Font sizedFontTexto = customFont.deriveFont(Font.BOLD, 16f); 
                    Font sizedFontTexto2 = customFont.deriveFont(Font.BOLD, 12f); 

                    // 4. Aplicar la fuente al JLabel creado en el diseñador
                    
                    // titulo del header 
                    titulo.setFont(sizedFontTitulo); 
                    
                    // texto del paso 2
                    textoPaso2.setFont(sizedFontTexto);
                    textoPaso2.setForeground(java.awt.Color.WHITE);
                    texto2Paso2.setFont(sizedFontTexto);
                    texto2Paso2.setForeground(java.awt.Color.WHITE);
                    
                    // texto a la derecha del paso 2
                    paso2DerTexto1.setFont(sizedFontTexto2);
                    paso2DerTexto2.setFont(sizedFontTexto2);
                    paso2DerTexto3.setFont(sizedFontTexto2);
                    
                    // texto central
                    paso2TextoCentral1.setFont(sizedFontTexto2);
                    paso2TextoCentral2.setFont(sizedFontTexto2);
                    paso2TextoCentral3.setFont(sizedFontTexto2);
                    paso2TextoCentral4.setFont(sizedFontTexto2);
                    paso2TextoCentral5.setFont(sizedFontTexto2);
                    paso2TextoCentral6.setFont(sizedFontTexto2);
                    
                    //botones
                    anteriorBtn.setFont(sizedFontTexto);
                    siguienteBtn.setFont(sizedFontTexto);
                } else {
                    System.err.println("Error: Archivo de fuente no encontrado en la ruta /fonts/PressStart2P.ttf");
                }

            } catch (Exception e) {
                // Captura errores como problemas de formato de fuente o I/O
                System.err.println("Error al cargar la fuente: " + e.getMessage());
            }
        
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        contenido = new javax.swing.JPanel();
        siguienteBtn = new javax.swing.JButton();
        paso2 = new javax.swing.JPanel();
        textoPaso2 = new javax.swing.JLabel();
        texto2Paso2 = new javax.swing.JLabel();
        paso2Der = new javax.swing.JPanel();
        paso2DerTexto1 = new javax.swing.JLabel();
        paso2DerTexto2 = new javax.swing.JLabel();
        paso2DerTexto3 = new javax.swing.JLabel();
        paso2TextoCentral1 = new javax.swing.JLabel();
        paso2TextoCentral2 = new javax.swing.JLabel();
        paso2TextoCentral3 = new javax.swing.JLabel();
        paso2TextoCentral4 = new javax.swing.JLabel();
        paso2TextoCentral5 = new javax.swing.JLabel();
        paso2TextoCentral6 = new javax.swing.JLabel();
        anteriorBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo.setBackground(new java.awt.Color(255, 255, 255));

        header.setBackground(new java.awt.Color(185, 188, 240));

        titulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Tutorial del Juego");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(titulo)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        contenido.setBackground(new java.awt.Color(255, 255, 255));

        siguienteBtn.setBackground(new java.awt.Color(94, 195, 246));
        siguienteBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        siguienteBtn.setText("Siguiente");
        siguienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteBtnActionPerformed(evt);
            }
        });

        paso2.setBackground(new java.awt.Color(51, 51, 255));
        paso2.setToolTipText("");

        textoPaso2.setText("Paso 2: ");

        texto2Paso2.setText("¿Cómo Jugarlo?");

        javax.swing.GroupLayout paso2Layout = new javax.swing.GroupLayout(paso2);
        paso2.setLayout(paso2Layout);
        paso2Layout.setHorizontalGroup(
            paso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paso2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(paso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paso2Layout.createSequentialGroup()
                        .addComponent(texto2Paso2)
                        .addGap(0, 21, Short.MAX_VALUE))
                    .addComponent(textoPaso2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        paso2Layout.setVerticalGroup(
            paso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paso2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(textoPaso2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(texto2Paso2)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        paso2Der.setBackground(new java.awt.Color(255, 255, 255));

        paso2DerTexto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paso2DerTexto1.setText("En base a las deciciones del ");

        paso2DerTexto2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paso2DerTexto2.setText("jugador se administrará el");

        paso2DerTexto3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paso2DerTexto3.setText("proyecto propuesto");

        javax.swing.GroupLayout paso2DerLayout = new javax.swing.GroupLayout(paso2Der);
        paso2Der.setLayout(paso2DerLayout);
        paso2DerLayout.setHorizontalGroup(
            paso2DerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paso2DerLayout.createSequentialGroup()
                .addGroup(paso2DerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paso2DerLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(paso2DerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(paso2DerTexto1, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                            .addComponent(paso2DerTexto3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(paso2DerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(paso2DerTexto2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        paso2DerLayout.setVerticalGroup(
            paso2DerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paso2DerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paso2DerTexto1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paso2DerTexto2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(paso2DerTexto3)
                .addContainerGap())
        );

        paso2TextoCentral1.setBackground(new java.awt.Color(255, 255, 255));
        paso2TextoCentral1.setText("Existen escenarios de las etapas respectivas de las ");

        paso2TextoCentral2.setText("metodologías");

        paso2TextoCentral3.setText("1. Planificación");

        paso2TextoCentral4.setBackground(new java.awt.Color(255, 255, 255));
        paso2TextoCentral4.setText("2. Ejecución");

        paso2TextoCentral5.setBackground(new java.awt.Color(255, 255, 255));
        paso2TextoCentral5.setText("3. Monitoreo y Control");

        paso2TextoCentral6.setBackground(new java.awt.Color(255, 255, 255));
        paso2TextoCentral6.setText("4. Cierre del Proyecto");

        anteriorBtn.setBackground(new java.awt.Color(94, 195, 246));
        anteriorBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        anteriorBtn.setText("Anterior");
        anteriorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(contenido);
        contenido.setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenidoLayout.createSequentialGroup()
                .addGroup(contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenidoLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(paso2TextoCentral5)
                            .addComponent(paso2TextoCentral6)
                            .addComponent(paso2TextoCentral2)
                            .addComponent(paso2TextoCentral3)
                            .addComponent(paso2TextoCentral4)
                            .addComponent(paso2TextoCentral1)
                            .addGroup(contenidoLayout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(anteriorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(siguienteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(contenidoLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(paso2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(paso2Der, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenidoLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(paso2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paso2Der, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89)
                .addComponent(paso2TextoCentral1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paso2TextoCentral2)
                .addGap(18, 18, 18)
                .addComponent(paso2TextoCentral3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(paso2TextoCentral4)
                .addGap(18, 18, 18)
                .addComponent(paso2TextoCentral5)
                .addGap(18, 18, 18)
                .addComponent(paso2TextoCentral6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anteriorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(siguienteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void siguienteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_siguienteBtnActionPerformed

    private void anteriorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorBtnActionPerformed
        // TODO add your handling code here:
        // 1. Crear una instancia de la vieja ventana (Paso1)
        Paso1 lastFrame = new Paso1();

        // 2. Hacer visible la vieja ventana
        lastFrame.setVisible(true);

        // 3. Ocultar la ventana actual (la clase Paso1)
        // 'this' se refiere a la instancia actual de Paso1
        this.dispose();
    }//GEN-LAST:event_anteriorBtnActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Paso2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anteriorBtn;
    private javax.swing.JPanel contenido;
    private javax.swing.JPanel fondo;
    private javax.swing.JPanel header;
    private javax.swing.JPanel paso2;
    private javax.swing.JPanel paso2Der;
    private javax.swing.JLabel paso2DerTexto1;
    private javax.swing.JLabel paso2DerTexto2;
    private javax.swing.JLabel paso2DerTexto3;
    private javax.swing.JLabel paso2TextoCentral1;
    private javax.swing.JLabel paso2TextoCentral2;
    private javax.swing.JLabel paso2TextoCentral3;
    private javax.swing.JLabel paso2TextoCentral4;
    private javax.swing.JLabel paso2TextoCentral5;
    private javax.swing.JLabel paso2TextoCentral6;
    private javax.swing.JButton siguienteBtn;
    private javax.swing.JLabel texto2Paso2;
    private javax.swing.JLabel textoPaso2;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
