/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces.tutorial;
import interfaces.*;
import java.awt.Font;
import java.io.InputStream;
import javax.swing.JPanel;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.Color;
import java.awt.GraphicsEnvironment;
/**
 *
 * @author frann
 */
public class Paso1 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Paso1.class.getName());

    /**
     * Creates new form prueba
     */
    public Paso1() {
        initComponents();
        this.setLocationRelativeTo(null); // abrir ventana en el centro 
        this.setTitle("PMySCRUM - Tutorial");
        
            // ===============================================
            // CÓDIGO PARA CARGAR Y APLICAR LA FUENTE EXTERNA
            // ===============================================
            try {
                // 1. Obtener el flujo de datos (InputStream) de la fuente desde el JAR
                InputStream is = Paso1.class.getResourceAsStream("/fonts/PressStart2P.ttf");

                // Verifica que la ruta es correcta; si is es null, el archivo no se encontró.
                if (is != null) {
                    // 2. Crear un objeto Font a partir del archivo
                    Font customFont = Font.createFont(Font.TRUETYPE_FONT, is);

                    // 3. Establecer el tamaño y estilo (ej. tamaño 24)
                    Font sizedFontTitulo = customFont.deriveFont(Font.BOLD, 24f); 
                    Font sizedFontTexto = customFont.deriveFont(Font.BOLD, 16f); 
                    Font sizedFontTexto2 = customFont.deriveFont(Font.BOLD, 12f); 

                    // 4. Aplicar la fuente al JLabel creado en el diseñador
                    
                    // titulo del header 
                    titulo.setFont(sizedFontTitulo); 
                    
                    // texto del paso 1
                    GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
                    ge.registerFont(customFont);
                    textoPaso1.setFont(sizedFontTexto);  
                    textoPaso1.setText("<html>" +
                        "<div style='text-align:left; font-family:\"" + customFont.getName() + "\"; font-size:12pt;'>" +
                        "<p style='margin:0 0 10px 0;'>Paso 1: </p>" +
                        "<p style='margin:0;'>Escoger Metodología</p>" + 
                        "</div></html>");
                    
                    // texto de instrucciones (debajo de paso 1)
                    texto.setFont(sizedFontTexto);
                    texto.setText("<html>" +
                        "<div style='text-align:center; font-family:\"" + customFont.getName() + "\";'>" +
                        "<p style='margin:0 0 10px 0;'>Elegir la metodología SCRUM o PMBOK </p>" +
                        "<p style='margin:0;'>Del caso propuesto</p>" + 
                        "</div></html>");                   
                    // botones
                    anteriorBtn.setFont(sizedFontTexto);
                    siguienteBtn.setFont(sizedFontTexto);
                } else {
                    System.err.println("Error: Archivo de fuente no encontrado en la ruta /fonts/PressStart2P.ttf");
                }

            } catch (Exception e) {
                // Captura errores como problemas de formato de fuente o I/O
                System.err.println("Error al cargar la fuente: " + e.getMessage());
            }
        
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        contenido = new javax.swing.JPanel();
        siguienteBtn = new javax.swing.JButton();
        texto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        anteriorBtn = new javax.swing.JButton();
        Paso1 = new classes.PanelRound();
        textoPaso1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo.setBackground(new java.awt.Color(255, 255, 255));

        header.setBackground(new java.awt.Color(185, 188, 240));

        titulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Tutorial del Juego");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE)
                .addContainerGap())
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(titulo)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        contenido.setBackground(new java.awt.Color(255, 255, 255));

        siguienteBtn.setBackground(new java.awt.Color(94, 195, 246));
        siguienteBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        siguienteBtn.setText("Siguiente");
        siguienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteBtnActionPerformed(evt);
            }
        });

        texto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/paso1.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(300, 200));

        anteriorBtn.setBackground(new java.awt.Color(94, 195, 246));
        anteriorBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        anteriorBtn.setText("Anterior");
        anteriorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorBtnActionPerformed(evt);
            }
        });

        Paso1.setBackground(new java.awt.Color(51, 51, 255));
        Paso1.setForeground(new java.awt.Color(255, 255, 255));
        Paso1.setRoundBottomLeft(50);
        Paso1.setRoundBottomRight(50);
        Paso1.setRoundTopLeft(50);
        Paso1.setRoundTopRight(50);

        textoPaso1.setForeground(new java.awt.Color(255, 255, 255));
        textoPaso1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout Paso1Layout = new javax.swing.GroupLayout(Paso1);
        Paso1.setLayout(Paso1Layout);
        Paso1Layout.setHorizontalGroup(
            Paso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Paso1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(textoPaso1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        Paso1Layout.setVerticalGroup(
            Paso1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Paso1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(textoPaso1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(contenido);
        contenido.setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(texto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(contenidoLayout.createSequentialGroup()
                .addGroup(contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenidoLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(anteriorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(siguienteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contenidoLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(Paso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Paso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(texto, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anteriorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(siguienteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(1421, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contenido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void siguienteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteBtnActionPerformed
        // TODO add your handling code here:
        // 1. Crear una instancia de la nueva ventana (Paso2)
        Paso2 nextFrame = new Paso2();

        // 2. Hacer visible la nueva ventana
        nextFrame.setVisible(true);

        // 3. Ocultar la ventana actual (la clase Paso1)
        // 'this' se refiere a la instancia actual de Paso1
        this.dispose();
    }//GEN-LAST:event_siguienteBtnActionPerformed

    private void anteriorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorBtnActionPerformed
        // TODO add your handling code here:
        // 1. Crear una instancia de la vieja ventana (Introduccion)
        Introduccion lastFrame = new Introduccion();

        // 2. Hacer visible la vieja ventana
        lastFrame.setVisible(true);

        // 3. Ocultar la ventana actual (la clase Paso1)
        // 'this' se refiere a la instancia actual de Paso1
        this.dispose();
    }//GEN-LAST:event_anteriorBtnActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Paso1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private classes.PanelRound Paso1;
    private javax.swing.JButton anteriorBtn;
    private javax.swing.JPanel contenido;
    private javax.swing.JPanel fondo;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton siguienteBtn;
    private javax.swing.JLabel texto;
    private javax.swing.JLabel textoPaso1;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
