/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces.tutorial;
import java.awt.Font;
import java.io.InputStream;
import java.awt.GraphicsEnvironment;
/**
 *
 * @author frann
 */
public class Paso2 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Paso2.class.getName());

    /**
     * Creates new form prueba
     */
    public Paso2() {
        initComponents();
        this.setLocationRelativeTo(null); // abrir ventana en el centro 
        this.setTitle("PMySCRUM - Tutorial");
        
            // ===============================================
            // CÓDIGO PARA CARGAR Y APLICAR LA FUENTE EXTERNA
            // ===============================================
            try {
                // 1. Obtener el flujo de datos (InputStream) de la fuente desde el JAR
                InputStream is = Paso2.class.getResourceAsStream("/fonts/PressStart2P.ttf");

                // Verifica que la ruta es correcta; si is es null, el archivo no se encontró.
                if (is != null) {
                    // 2. Crear un objeto Font a partir del archivo
                    Font customFont = Font.createFont(Font.TRUETYPE_FONT, is);

                    // 3. Establecer el tamaño y estilo (ej. tamaño 24)
                    Font sizedFontTitulo = customFont.deriveFont(Font.BOLD, 24f); 
                    Font sizedFontTexto = customFont.deriveFont(Font.BOLD, 12f); 
                    Font sizedFontBoton = customFont.deriveFont(Font.BOLD, 15f); 

                    // 4. Aplicar la fuente al JLabel creado en el diseñador
                    
                    // titulo del header 
                    titulo.setFont(sizedFontTitulo); 
                    
                    // texto del paso 2
                    GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
                    ge.registerFont(customFont);
                    textoPaso2.setFont(sizedFontTexto);
                    textoPaso2.setText("<html>" +
                        "<div style='text-align:left; font-family:\"" + customFont.getName() + "\";'>" +
                        "<p style='margin:0 0 10px 0;'>Paso 2: </p>" +
                        "<p style='margin:0;'>¿Cómo Jugarlo?</p>" + 
                        "</div></html>");
                    

                    // texto a la derecha del paso 2
                    paso2DerTexto.setFont(sizedFontTexto);
                    paso2DerTexto.setText("<html>" +
                        "<div style='text-align:center; font-family:\"" + customFont.getName() + "\";'>" +
                        "<p style='margin:0 0 10px 0;'>En base a las decisiones del</p>" +
                        "<p style='margin:0 0 10px 0;'>jugador se administrará el</p>" +
                        "<p style='margin:0;'>proyecto propuesto</p>" + 
                        "</div></html>");
                    
                    // texto central
                    paso2TextoCentral.setFont(sizedFontTexto);
                    paso2TextoCentral.setText("<html>" +
                        "<div style='text-align:left; font-family:\"" + customFont.getName() + "\";'>" +
                        "<p style='margin:0 0 10px 0;'>Existen escenarios de las etapas respectivas</p>" +
                        "<p style='margin:0 0 10px 0;'>de las metodologías</p>" +
                        "<p style='margin:0 0 10px 0;'>1. Planificación</p>" +
                        "<p style='margin:0 0 10px 0;'>2. Ejecución</p>" +
                        "<p style='margin:0 0 10px 0;'>3. Monitoreo y Control</p>" +
                        "<p style='margin:0;'>4. Cierre del Proyecto</p>" + 
                        "</div></html>");
                    
                    //botones
                    anteriorBtn.setFont(sizedFontBoton);
                    siguienteBtn.setFont(sizedFontBoton);
                } else {
                    System.err.println("Error: Archivo de fuente no encontrado en la ruta /fonts/PressStart2P.ttf");
                }

            } catch (Exception e) {
                // Captura errores como problemas de formato de fuente o I/O
                System.err.println("Error al cargar la fuente: " + e.getMessage());
            }
        
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        contenido = new javax.swing.JPanel();
        paso2 = new classes.PanelRound();
        textoPaso2 = new javax.swing.JLabel();
        paso2Der = new javax.swing.JPanel();
        paso2DerTexto = new javax.swing.JLabel();
        paso2TextoCentral = new javax.swing.JLabel();
        anteriorBtn = new javax.swing.JButton();
        siguienteBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo.setBackground(new java.awt.Color(255, 255, 255));

        header.setBackground(new java.awt.Color(185, 188, 240));

        titulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Tutorial del Juego");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(titulo)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        contenido.setBackground(new java.awt.Color(255, 255, 255));

        paso2.setBackground(new java.awt.Color(51, 51, 255));
        paso2.setRoundBottomLeft(50);
        paso2.setRoundBottomRight(50);
        paso2.setRoundTopLeft(50);
        paso2.setRoundTopRight(50);

        textoPaso2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout paso2Layout = new javax.swing.GroupLayout(paso2);
        paso2.setLayout(paso2Layout);
        paso2Layout.setHorizontalGroup(
            paso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paso2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(textoPaso2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        paso2Layout.setVerticalGroup(
            paso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paso2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoPaso2, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addContainerGap())
        );

        paso2Der.setBackground(new java.awt.Color(255, 255, 255));
        paso2Der.setPreferredSize(new java.awt.Dimension(306, 75));

        paso2DerTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout paso2DerLayout = new javax.swing.GroupLayout(paso2Der);
        paso2Der.setLayout(paso2DerLayout);
        paso2DerLayout.setHorizontalGroup(
            paso2DerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paso2DerLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(paso2DerTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                .addContainerGap())
        );
        paso2DerLayout.setVerticalGroup(
            paso2DerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paso2DerTexto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        paso2TextoCentral.setBackground(new java.awt.Color(255, 255, 255));
        paso2TextoCentral.setText("}");

        anteriorBtn.setBackground(new java.awt.Color(94, 195, 246));
        anteriorBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        anteriorBtn.setText("Anterior");
        anteriorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorBtnActionPerformed(evt);
            }
        });

        siguienteBtn.setBackground(new java.awt.Color(94, 195, 246));
        siguienteBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        siguienteBtn.setText("Siguiente");
        siguienteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(contenido);
        contenido.setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenidoLayout.createSequentialGroup()
                .addGroup(contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenidoLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(anteriorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(siguienteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contenidoLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(paso2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(paso2Der, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contenidoLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(paso2TextoCentral, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenidoLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(paso2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paso2Der, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(48, 48, 48)
                .addComponent(paso2TextoCentral, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                .addGap(53, 53, 53)
                .addGroup(contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anteriorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(siguienteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void siguienteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteBtnActionPerformed
        // TODO add your handling code here:
        // 1. Crear una instancia de la nueva ventana (Paso3)
        Paso3 nextFrame = new Paso3();

        // 2. Hacer visible la nueva ventana
        nextFrame.setVisible(true);

        // 3. Ocultar la ventana actual (la clase Paso1)
        // 'this' se refiere a la instancia actual de Paso1
        this.dispose();
    }//GEN-LAST:event_siguienteBtnActionPerformed

    private void anteriorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorBtnActionPerformed
        // TODO add your handling code here:
        // 1. Crear una instancia de la vieja ventana (Paso1)
        Paso1 lastFrame = new Paso1();

        // 2. Hacer visible la vieja ventana
        lastFrame.setVisible(true);

        // 3. Ocultar la ventana actual (la clase Paso1)
        // 'this' se refiere a la instancia actual de Paso1
        this.dispose();
    }//GEN-LAST:event_anteriorBtnActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Paso2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anteriorBtn;
    private javax.swing.JPanel contenido;
    private javax.swing.JPanel fondo;
    private javax.swing.JPanel header;
    private classes.PanelRound paso2;
    private javax.swing.JPanel paso2Der;
    private javax.swing.JLabel paso2DerTexto;
    private javax.swing.JLabel paso2TextoCentral;
    private javax.swing.JButton siguienteBtn;
    private javax.swing.JLabel textoPaso2;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
