/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces.tutorial;
import java.awt.Font;
import java.io.InputStream;
import java.awt.GraphicsEnvironment;
/**
 *
 * @author frann
 */
public class Paso4 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Paso4.class.getName());

    /**
     * Creates new form prueba
     */
    public Paso4() {
        initComponents();
        this.setLocationRelativeTo(null); // abrir ventana en el centro 
        this.setTitle("PMySCRUM - Tutorial");
        
            // ===============================================
            // CÓDIGO PARA CARGAR Y APLICAR LA FUENTE EXTERNA
            // ===============================================
            try {
                // 1. Obtener el flujo de datos (InputStream) de la fuente desde el JAR
                InputStream is = Paso4.class.getResourceAsStream("/fonts/PressStart2P.ttf");

                // Verifica que la ruta es correcta; si is es null, el archivo no se encontró.
                if (is != null) {
                    // 2. Crear un objeto Font a partir del archivo
                    Font customFont = Font.createFont(Font.TRUETYPE_FONT, is);

                    // 3. Establecer el tamaño y estilo (ej. tamaño 24)
                    Font sizedFontTitulo = customFont.deriveFont(Font.BOLD, 24f); 
                    Font sizedFontTexto = customFont.deriveFont(Font.BOLD, 12f); 
                    Font sizedFontBoton = customFont.deriveFont(Font.BOLD, 15f); 

                    // 4. Aplicar la fuente al JLabel creado en el diseñador
                    
                    // titulo del header 
                    titulo.setFont(sizedFontTitulo); 
                    
                    // texto del paso 4
                    GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
                    ge.registerFont(customFont);
                    textoPaso4.setFont(sizedFontTexto);
                    textoPaso4.setText("<html>" +
                        "<div style='text-align:left; font-family:\"" + customFont.getName() + "\";'>" +
                        "<p style='margin:0 0 10px 0;'>Paso 4: </p>" +
                        "<p style='margin:0 0 10px 0;'>Resultados y </p>" + 
                        "<p style='margin:0;'>Retroalimentación</p>" + 
                        "</div></html>");
                    
                    
                    // texto central
                    paso4TextoCentral.setFont(sizedFontTexto);
                    paso4TextoCentral.setText("<html>" +
                        "<div style='text-align:center; font-family:\"" + customFont.getName() + "\";'>" +
                        "<p style='margin:0 0 10px 0;'>Verás si tus deciciones fueron un benecicio o si</p>" +
                        "<p style='margin:0 0 15px 0;'>afectaron el proyecto</p>" + 
                        "<p style='margin:0 0 10px 0;'>Tu resultado es tu retroalimentación</p>" + 
                        "<p style='margin:0;'>¡Aprende con ella!</p>" + 
                        "</div></html>");
                    
                    // boton jugar
                    jugarBtn.setFont(sizedFontBoton);
                    
                } else {
                    System.err.println("Error: Archivo de fuente no encontrado en la ruta /fonts/PressStart2P.ttf");
                }

            } catch (Exception e) {
                // Captura errores como problemas de formato de fuente o I/O
                System.err.println("Error al cargar la fuente: " + e.getMessage());
            }
        
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        contenido = new javax.swing.JPanel();
        paso4 = new classes.PanelRound();
        textoPaso4 = new javax.swing.JLabel();
        paso4TextoCentral = new javax.swing.JLabel();
        imagen = new javax.swing.JLabel();
        jugarBtn = new classes.ButtonRound();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo.setBackground(new java.awt.Color(255, 255, 255));

        header.setBackground(new java.awt.Color(185, 188, 240));

        titulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 0, 0));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Tutorial del Juego");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(titulo)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        contenido.setBackground(new java.awt.Color(255, 255, 255));

        paso4.setBackground(new java.awt.Color(51, 51, 255));
        paso4.setRoundBottomLeft(50);
        paso4.setRoundBottomRight(50);
        paso4.setRoundTopLeft(50);
        paso4.setRoundTopRight(50);

        textoPaso4.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout paso4Layout = new javax.swing.GroupLayout(paso4);
        paso4.setLayout(paso4Layout);
        paso4Layout.setHorizontalGroup(
            paso4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paso4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(textoPaso4, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        paso4Layout.setVerticalGroup(
            paso4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paso4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(textoPaso4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        paso4TextoCentral.setBackground(new java.awt.Color(255, 255, 255));
        paso4TextoCentral.setForeground(new java.awt.Color(0, 0, 0));
        paso4TextoCentral.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paso4TextoCentral.setText("Verás si tus decisiones fueron un beneficio o si");

        imagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/retro.png"))); // NOI18N

        jugarBtn.setBackground(new java.awt.Color(51, 255, 51));
        jugarBtn.setForeground(new java.awt.Color(255, 255, 255));
        jugarBtn.setText("Jugar Ahora");
        jugarBtn.setRoundBottomLeft(50);
        jugarBtn.setRoundBottomRight(50);
        jugarBtn.setRoundTopLeft(50);
        jugarBtn.setRoundTopRight(50);
        jugarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jugarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(contenido);
        contenido.setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenidoLayout.createSequentialGroup()
                .addComponent(paso4TextoCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenidoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jugarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(267, 267, 267))
            .addGroup(contenidoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(paso4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(imagen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenidoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(paso4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(paso4TextoCentral, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(imagen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jugarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jugarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jugarBtnActionPerformed
        // TODO add your handling code here:
        // 1. Crear una instancia de la nueva ventana (paso1)
        Paso1 nextFrame = new Paso1();

        // 2. Hacer visible la nueva ventana
        nextFrame.setVisible(true);

        // 3. Ocultar la ventana actual (la clase Paso1)
        // 'this' se refiere a la instancia actual de Paso1
        this.dispose();
    }//GEN-LAST:event_jugarBtnActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Paso4().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenido;
    private javax.swing.JPanel fondo;
    private javax.swing.JPanel header;
    private javax.swing.JLabel imagen;
    private classes.ButtonRound jugarBtn;
    private classes.PanelRound paso4;
    private javax.swing.JLabel paso4TextoCentral;
    private javax.swing.JLabel textoPaso4;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
